export const data = [
  {
    "mien": "buoz",
    "eng": "hand",
    "pos": "noun",
    "ipa": "buoz",
    "mex1": "Koi meih nyei buoz.",
    "mtr1": "Open your hand.",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "cie",
    "eng": "car",
    "pos": "noun",
    "ipa": "ciə˧",
    "mex1": "Meih haih cap cie nie?",
    "mtr1": "Do you know how to drive a car?",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "dang",
    "eng": "light",
    "pos": "noun",
    "ipa": "tɐŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "faang",
    "eng": "Suitcase, chest",
    "pos": "noun",
    "ipa": "faŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gaengv",
    "eng": "frog",
    "pos": "noun",
    "ipa": "k’æŋ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "heh",
    "eng": "shoe",
    "pos": "noun",
    "ipa": "he˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hiun",
    "eng": "ring",
    "pos": "noun",
    "ipa": "hiun˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hlaax",
    "eng": "month",
    "pos": "noun",
    "ipa": "l̥a˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hmien",
    "eng": "face",
    "pos": "noun",
    "ipa": "m̥iən˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnaav",
    "eng": "crossbow",
    "pos": "noun",
    "ipa": "n̥a˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hngaqv",
    "eng": "chop",
    "pos": "Apply for Job",
    "ipa": "ŋ̊ɐʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnyouv",
    "eng": "heart",
    "pos": "noun",
    "ipa": "ɲ̥əu˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "huingx",
    "eng": "Garden",
    "pos": "noun",
    "ipa": "huiŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "jaux",
    "eng": "Egg",
    "pos": "noun",
    "ipa": "t͡ɕaʊ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "korqv",
    "eng": "gourd",
    "pos": "noun",
    "ipa": "kʰɒʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "lui",
    "eng": "Horse",
    "pos": "noun",
    "ipa": "lui˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "maaz",
    "eng": "shirt",
    "pos": "noun",
    "ipa": "ma˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbing",
    "eng": "monkey",
    "pos": "noun",
    "ipa": "biŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "naauz",
    "eng": "mouse",
    "pos": "noun",
    "ipa": "naːʊ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ndiangx",
    "eng": "tree",
    "pos": "noun",
    "ipa": "diɐŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ngongh",
    "eng": "Cow",
    "pos": "noun",
    "ipa": "ŋoŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "njiuz",
    "eng": "Scissors",
    "pos": "noun",
    "ipa": "d͡ʑiu˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nqaai",
    "eng": "dry",
    "pos": "adjective",
    "ipa": "gaːɪ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyaah",
    "eng": "teeth",
    "pos": "noun",
    "ipa": "ɲa˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nzangv",
    "eng": "canoe",
    "pos": "noun",
    "ipa": "d͡zɐŋ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "porng",
    "eng": "hoe",
    "pos": "noun",
    "ipa": "b’ɒŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "qaa",
    "eng": "shrimp",
    "pos": "noun",
    "ipa": "t͡ɕʰa˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "sou",
    "eng": "book",
    "pos": "noun",
    "ipa": "səu˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "tei",
    "eng": "ladder",
    "pos": "noun",
    "ipa": "tʰɛɪ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "waac",
    "eng": "language",
    "pos": "noun",
    "ipa": "wa˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "yungh",
    "eng": "Goat",
    "pos": "noun",
    "ipa": "juŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "zaandgz",
    "eng": "Elephant",
    "pos": "noun",
    "ipa": "zadk’˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "yie",
    "eng": "I",
    "pos": "pronoun",
    "ipa": "jiə˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "yienv",
    "eng": "Bowl",
    "pos": "noun",
    "ipa": "jiən˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "yietc",
    "eng": "One",
    "pos": "number",
    "ipa": "jietʰ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "oix",
    "eng": "To want",
    "pos": "verb",
    "ipa": "oɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "meih",
    "eng": "you",
    "pos": "pronoun",
    "ipa": "mɛɪ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ndouv",
    "eng": "to gamble",
    "pos": "verb",
    "ipa": "dəu˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nduov",
    "eng": "to trick into something",
    "pos": "verb",
    "ipa": "duə˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gorngv",
    "eng": "To speak",
    "pos": "verb",
    "ipa": "k’ɒŋ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnoi",
    "eng": "Day",
    "pos": "noun",
    "ipa": "n̥oɪ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnoi-hnoi",
    "eng": "Day by day, everyday",
    "pos": "adverb",
    "ipa": "n̥oɪ-n̥oɪ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "fu’jueiv",
    "eng": "kids",
    "pos": "noun",
    "ipa": "fu’t͡ɕuɛɪ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "bun",
    "eng": "for",
    "pos": "",
    "ipa": "b’un˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hoqc",
    "eng": "to learn",
    "pos": "verb",
    "ipa": "hoʔ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyei",
    "eng": "possessive particle",
    "pos": "Particle",
    "ipa": "ɲɛɪ˧",
    "mex1": "Yie nyei",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyei",
    "eng": "Manner particle",
    "pos": "Particle",
    "ipa": "ɲɛɪ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ih",
    "eng": "this, now",
    "pos": "Adjective",
    "ipa": "i˧˩",
    "mex1": "Ih jaax mienh maiv haih gorngv mbuo nyei waac.",
    "mtr1": "Today’s Mien people can’t speak our language.",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbuo",
    "eng": "Plural (yie mbuo - we, ninh mbuo - they)",
    "pos": "pronoun",
    "ipa": "buə˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "biaa",
    "eng": "five",
    "pos": "number",
    "ipa": "b’ia˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "joux",
    "eng": "Word",
    "pos": "noun",
    "ipa": "t͡ɕəu˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "lomh nzoih",
    "eng": "Together",
    "pos": "adjetive",
    "ipa": "lom˧˩ d͡zoɪ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "daaih",
    "eng": "to come",
    "pos": "verb",
    "ipa": "taːɪ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "caux",
    "eng": "To speak",
    "pos": "verb",
    "ipa": "caʊ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nzaangc",
    "eng": "Writing",
    "pos": "noun",
    "ipa": "d͡zaŋ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "a’hneiv",
    "eng": "happy",
    "pos": "adjective",
    "ipa": "ɐ’n̥ɛɪ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gengh",
    "eng": "very",
    "pos": "adjective",
    "ipa": "k’eŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "haiz",
    "eng": "To be (feeling)",
    "pos": "verb",
    "ipa": "haɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "aengx",
    "eng": "again",
    "pos": "Adverb",
    "ipa": "æŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "doqc",
    "eng": "to read",
    "pos": "verb",
    "ipa": "toʔ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "siepv",
    "eng": "fast",
    "pos": "adjective",
    "ipa": "siəb’˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "oc",
    "eng": "Ok?, all right? (commanding acknowledgement)",
    "pos": "particle",
    "ipa": "o˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "dorng",
    "eng": "End",
    "pos": "Noun",
    "ipa": "tɒŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "buangh",
    "eng": "To meet",
    "pos": "verb",
    "ipa": "b’uɐŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "laengz zingh",
    "eng": "Thank you, thanks",
    "pos": "",
    "ipa": "læŋ˨˧ ziŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "muangx",
    "eng": "To listen",
    "pos": "verb",
    "ipa": "muɐŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ndaangc",
    "eng": "Beforehand, first",
    "pos": "",
    "ipa": "daŋ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nzunc",
    "eng": "Once, (one) time",
    "pos": "",
    "ipa": "d͡zun˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gan",
    "eng": "To follow",
    "pos": "verb",
    "ipa": "k’ɐn˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ninh",
    "eng": "He/she",
    "pos": "Pronoun",
    "ipa": "nin˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyanc",
    "eng": "To eat",
    "pos": "verb",
    "ipa": "ɲɐn˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "njuov",
    "eng": "cake",
    "pos": "noun",
    "ipa": "d͡ʑuə˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gaam",
    "eng": "sweet",
    "pos": "Adjective",
    "ipa": "k’am˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "yie mbuo",
    "eng": "we",
    "pos": "pronoun",
    "ipa": "jiə˧ buə˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "caux",
    "eng": "and",
    "pos": "",
    "ipa": "tsʰaʊ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "fiev",
    "eng": "To write",
    "pos": "",
    "ipa": "fiə˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "donc",
    "eng": "Slow",
    "pos": "adjective",
    "ipa": "ton˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "Yaac",
    "eng": "Will (future marker)",
    "pos": "",
    "ipa": "ja˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "borqv",
    "eng": "To hit",
    "pos": "",
    "ipa": "b’ɒʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mingh",
    "eng": "to go",
    "pos": "",
    "ipa": "miŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnamv",
    "eng": "to love",
    "pos": "",
    "ipa": "n̥ɐm˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "lorz",
    "eng": "to find",
    "pos": "",
    "ipa": "lɒ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "maaiz",
    "eng": "to buy",
    "pos": "",
    "ipa": "maːɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "siang",
    "eng": "New",
    "pos": "",
    "ipa": "siɐŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gaengh",
    "eng": "door",
    "pos": "",
    "ipa": "k’æŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "dungx",
    "eng": "don’t",
    "pos": "",
    "ipa": "tuŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "dungz",
    "eng": "Pig",
    "pos": "",
    "ipa": "tuŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "bungx",
    "eng": "to let go",
    "pos": "",
    "ipa": "b’uŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "bungz",
    "eng": "Saefong",
    "pos": "",
    "ipa": "b’uŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nzaangc qiex",
    "eng": "Written tone, tone",
    "pos": "",
    "ipa": "d͡zaŋ˨˩ t͡ɕʰiə˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "qiex",
    "eng": "Voice",
    "pos": "",
    "ipa": "t͡ɕʰiə˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gauv",
    "eng": "Kao, first son",
    "pos": "",
    "ipa": "k’aʊ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gaux",
    "eng": "Enough, sufficient",
    "pos": "",
    "ipa": "k’aʊ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gauh",
    "eng": "More, -er",
    "pos": "",
    "ipa": "k’aʊ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbaiv",
    "eng": "Bike?",
    "pos": "",
    "ipa": "baɪ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbaix",
    "eng": "to slap",
    "pos": "",
    "ipa": "baɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbaih",
    "eng": "to balance",
    "pos": "",
    "ipa": "baɪ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbaiz",
    "eng": "",
    "pos": "",
    "ipa": "baɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbaic",
    "eng": "to sit",
    "pos": "",
    "ipa": "baɪ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "seix",
    "eng": "to try (and see), hard, life",
    "pos": "",
    "ipa": "sɛɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "aaux",
    "eng": "Nzangc-aaux: ending, word nucleus",
    "pos": "",
    "ipa": "aːʊ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "in",
    "eng": "Ciggarette",
    "pos": "",
    "ipa": "in˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "im",
    "eng": "bitter",
    "pos": "",
    "ipa": "im˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ba’daatc",
    "eng": "Bitter melon",
    "pos": "",
    "ipa": "b’ɐ’tatʰ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "don",
    "eng": "chair",
    "pos": "",
    "ipa": "ton˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "om",
    "eng": "Bruised",
    "pos": "",
    "ipa": "om˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "beu",
    "eng": "to wrap",
    "pos": "verb",
    "ipa": "b’ɜo˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ban",
    "eng": "to spoon",
    "pos": "verb",
    "ipa": "b’ɐn˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "baan",
    "eng": "",
    "pos": "",
    "ipa": "b’an˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "baaux",
    "eng": "to sing",
    "pos": "verb",
    "ipa": "b’aːʊ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "cien",
    "eng": "Kin, reative",
    "pos": "noun",
    "ipa": "ciən˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "cing",
    "eng": "to clear",
    "pos": "verb",
    "ipa": "ciŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "cingh",
    "eng": "Cingh-jaang: calf\nCingh-mborqc: knee",
    "pos": "",
    "ipa": "ciŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "cingv",
    "eng": "to hire",
    "pos": "verb",
    "ipa": "ciŋ˦˥",
    "mex1": "Yie cingv chan",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "dorn",
    "eng": "Boy, son",
    "pos": "noun",
    "ipa": "tɒn˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "dien",
    "eng": "A little, not very much",
    "pos": "adjective",
    "ipa": "tiən˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "die",
    "eng": "Father, dad, papa",
    "pos": "noun",
    "ipa": "tiə˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mienv",
    "eng": "Spirit, god",
    "pos": "noun",
    "ipa": "miən˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mienx",
    "eng": "precarious",
    "pos": "adjective",
    "ipa": "miən˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mienh",
    "eng": "People, Mien",
    "pos": "noun",
    "ipa": "miən˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "toux",
    "eng": "Rabbit",
    "pos": "noun",
    "ipa": "tʰəu˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "fun",
    "eng": "grandchildren",
    "pos": "noun",
    "ipa": "fun˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "funx",
    "eng": "garlic",
    "pos": "noun",
    "ipa": "fun˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "fioux",
    "eng": "to clean up, to tidy",
    "pos": "verb",
    "ipa": "fiəu˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gong",
    "eng": "Work",
    "pos": "Noun",
    "ipa": "k’oŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ong",
    "eng": "grandpa",
    "pos": "noun",
    "ipa": "oŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "haih",
    "eng": "Can, to be able to",
    "pos": "verb",
    "ipa": "haɪ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "haix",
    "eng": "to hear",
    "pos": "verb",
    "ipa": "haɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hiaang",
    "eng": "Part of a mien name",
    "pos": "",
    "ipa": "hiaŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "Hiaangx",
    "eng": "To grow bigger (big fire)",
    "pos": "verb",
    "ipa": "hiaŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hlan",
    "eng": "liver",
    "pos": "noun",
    "ipa": "l̥ɐn˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hlang",
    "eng": "Tall, high",
    "pos": "adjective",
    "ipa": "l̥ɐŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hlaang",
    "eng": "Rope, string",
    "pos": "noun",
    "ipa": "l̥aŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hmuangx",
    "eng": "Dark, night, opaque, not clear",
    "pos": "adjective",
    "ipa": "m̥uɐŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnangv",
    "eng": "Only",
    "pos": "",
    "ipa": "n̥ɐŋ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnaangx",
    "eng": "Cooked rice",
    "pos": "noun",
    "ipa": "n̥aŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "fih hnangv",
    "eng": "Similar, same",
    "pos": "",
    "ipa": "fi˧˩ n̥ɐŋ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnangv haaix",
    "eng": "How",
    "pos": "",
    "ipa": "n̥ɐŋ˦˥ haːɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "maiv",
    "eng": "Negative marker",
    "pos": "particle",
    "ipa": "maɪ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnganx",
    "eng": "",
    "pos": "",
    "ipa": "ŋ̊ɐn˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hniev",
    "eng": "Heavy",
    "pos": "",
    "ipa": "n̥iə˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hnyamx",
    "eng": "",
    "pos": "",
    "ipa": "ɲ̥ɐm˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hngongx",
    "eng": "Stupid, dumb",
    "pos": "adjective",
    "ipa": "ŋ̊oŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "huing",
    "eng": "to turn around, to circle around",
    "pos": "",
    "ipa": "huiŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "jauv",
    "eng": "Path, street",
    "pos": "",
    "ipa": "t͡ɕaʊ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "jiouh",
    "eng": "bridge",
    "pos": "",
    "ipa": "t͡ɕiəu˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "jiouc",
    "eng": "",
    "pos": "",
    "ipa": "t͡ɕiəu˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "cingh-jaa",
    "eng": "Wedding",
    "pos": "",
    "ipa": "tsʰiŋh-t͡ɕa˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "kung",
    "eng": "to spill",
    "pos": "",
    "ipa": "kʰuŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "kungx",
    "eng": "Have time",
    "pos": "",
    "ipa": "kʰuŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "kungh",
    "eng": "Keep doing, continue, continually",
    "pos": "",
    "ipa": "kʰuŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "lai",
    "eng": "vegetables",
    "pos": "",
    "ipa": "laɪ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "Laai",
    "eng": "Mien name Lai",
    "pos": "",
    "ipa": "laːɪ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ga’haav",
    "eng": "Behind, back",
    "pos": "",
    "ipa": "k’ɐ’ha˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbungv",
    "eng": "Bone",
    "pos": "",
    "ipa": "buŋ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbungh",
    "eng": "",
    "pos": "",
    "ipa": "buŋ˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "mbung",
    "eng": "dusty, polluted?",
    "pos": "",
    "ipa": "buŋ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "niaa",
    "eng": "Like that?",
    "pos": "",
    "ipa": "nia˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "biaav",
    "eng": "Stick",
    "pos": "",
    "ipa": "b’ia˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "a’lov",
    "eng": "(Exclamation to something bad or pitiful)",
    "pos": "",
    "ipa": "ɐ’lo˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "a’loc",
    "eng": "Used to",
    "pos": "",
    "ipa": "ɐ’lo˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "njiangx",
    "eng": "Bright",
    "pos": "",
    "ipa": "d͡ʑiɐŋ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "njiux",
    "eng": "to look in a direction (?)",
    "pos": "",
    "ipa": "d͡ʑiu˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "njiuc",
    "eng": "",
    "pos": "",
    "ipa": "d͡ʑiu˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyau",
    "eng": "To grab",
    "pos": "",
    "ipa": "ɲaʊ˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyauv",
    "eng": "Troublesome",
    "pos": "",
    "ipa": "ɲaʊ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyaux",
    "eng": "to wrinkle, to wither",
    "pos": "",
    "ipa": "ɲaʊ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyaah",
    "eng": "",
    "pos": "",
    "ipa": "ɲa˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "yietc",
    "eng": "one (primary set)",
    "pos": "noun / adjective",
    "ipa": "jiətʰ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "i",
    "eng": "two (primary set)",
    "pos": "noun / adjective",
    "ipa": "i˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "buo",
    "eng": "three (primary set)",
    "pos": "noun / adjective",
    "ipa": "b’uə˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "biei",
    "eng": "four (primary set)",
    "pos": "noun / adjective",
    "ipa": "b’iəi˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "biaa",
    "eng": "five (primary set)",
    "pos": "noun / adjective",
    "ipa": "b’ia˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "juqv",
    "eng": "six (primary set)",
    "pos": "noun / adjective",
    "ipa": "t͡ɕuʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "siec",
    "eng": "seven (primary set)",
    "pos": "noun / adjective",
    "ipa": "siə˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hietc",
    "eng": "eight (primary set)",
    "pos": "noun / adjective",
    "ipa": "hiətʰ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ndouh",
    "eng": "nine (primary set)",
    "pos": "noun / adjective",
    "ipa": "dəu˧˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc",
    "eng": "ten",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc yietc",
    "eng": "eleven",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩ jiətʰ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc nyeic",
    "eng": "twelve",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩ ɲɛɪ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc faam",
    "eng": "thirteen",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩ fam˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc feix",
    "eng": "fourteen",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩ fɛɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc hmz",
    "eng": "fifteen",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩ m̥˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc luoqc",
    "eng": "Sixteen",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩ luəʔ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc cietv",
    "eng": "seventeen",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩ tsʰiətʰ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc betv",
    "eng": "eighteen",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩ b’etʰ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc juov",
    "eng": "nineteen",
    "pos": "noun / adjective",
    "ipa": "ziəb’˨˩ t͡ɕuə˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyeic ziepc",
    "eng": "twenty",
    "pos": "noun / adjective",
    "ipa": "ɲɛɪ˨˩ ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "faah ziepc",
    "eng": "thirty",
    "pos": "noun / adjective",
    "ipa": "fam˧ ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "feix ziepc",
    "eng": "fourty",
    "pos": "noun / adjective",
    "ipa": "fɛɪ˨˧ ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hmz ziepc",
    "eng": "fifty",
    "pos": "noun / adjective",
    "ipa": "m̥˨˧ ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "luoqc ziepc",
    "eng": "sixty",
    "pos": "noun / adjective",
    "ipa": "luəʔ˨˩ ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "cietv ziepc",
    "eng": "seventy",
    "pos": "noun / adjective",
    "ipa": "ciətʰ˦˥ ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "baetz ziepc",
    "eng": "eighty",
    "pos": "noun / adjective",
    "ipa": "b’etʰ˦˥ ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "juov ziepc",
    "eng": "ninety",
    "pos": "noun / adjective",
    "ipa": "t͡ɕuə˦˥ ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "yietc baeqv",
    "eng": "One hundred",
    "pos": "noun / adjective",
    "ipa": "jiətʰ˨˩ b’æʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "primary +"
  },
  {
    "mien": "nyeic baeqv",
    "eng": "Two hundred",
    "pos": "noun / adjective",
    "ipa": "ɲɛɪ˨˩ b’æʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "secondary +"
  },
  {
    "mien": "faam baeqv",
    "eng": "Three hundred",
    "pos": "noun / adjective",
    "ipa": "fam˧ b’æʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "secondary +"
  },
  {
    "mien": "feix baeqv",
    "eng": "Four hundred",
    "pos": "noun / adjective",
    "ipa": "fɛɪ˨˧ b’æʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "secondary +"
  },
  {
    "mien": "hmz baeqv",
    "eng": "Five hundred",
    "pos": "noun / adjective",
    "ipa": "m̥˨˧ b’æʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "secondary +"
  },
  {
    "mien": "luoqc baeqv",
    "eng": "Six hundred",
    "pos": "noun / adjective",
    "ipa": "luəʔ˨˩ b’æʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "secondary +"
  },
  {
    "mien": "cietv baeqv",
    "eng": "Seven hundred",
    "pos": "noun / adjective",
    "ipa": "tsʰiətʰ˦˥ b’æʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "secondary +"
  },
  {
    "mien": "baetv baeqv",
    "eng": "Eight hundred",
    "pos": "noun / adjective",
    "ipa": "b’etʰ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "secondary +"
  },
  {
    "mien": "juov baeqv",
    "eng": "Nine hundred",
    "pos": "noun / adjective",
    "ipa": "t͡ɕuə˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "secondary +"
  },
  {
    "mien": "yietc cin",
    "eng": "One thousand",
    "pos": "noun / adjective",
    "ipa": "jiətʰ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "primary +"
  },
  {
    "mien": "i cin",
    "eng": "Two thousand",
    "pos": "noun / adjective",
    "ipa": "i˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "primary +"
  },
  {
    "mien": "buo cin",
    "eng": "three thousand",
    "pos": "noun / adjective",
    "ipa": "b’uə˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "primary +"
  },
  {
    "mien": "biei cin",
    "eng": "four thousand",
    "pos": "noun / adjective",
    "ipa": "b’iəi˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "primary +"
  },
  {
    "mien": "biaa cin",
    "eng": "five thousand",
    "pos": "noun / adjective",
    "ipa": "b’ia˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "primary +"
  },
  {
    "mien": "juqv cin",
    "eng": "Six thousand",
    "pos": "noun / adjective",
    "ipa": "t͡ɕuʔ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "primary +"
  },
  {
    "mien": "luoqc cin",
    "eng": "Seven thousand",
    "pos": "noun / adjective",
    "ipa": "luəʔ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "primary +"
  },
  {
    "mien": "ndough cin",
    "eng": "eight thousand",
    "pos": "noun / adjective",
    "ipa": "",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": "primary +"
  },
  {
    "mien": "juov cin",
    "eng": "nine thousand",
    "pos": "noun / adjective",
    "ipa": "t͡ɕuə˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "ziepc cin",
    "eng": "Ten thousand",
    "pos": "noun / adjective",
    "ipa": "",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "yietc waanc",
    "eng": "One hundred thousand",
    "pos": "noun / adjective",
    "ipa": "",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "yietc baeqv waanc",
    "eng": "One million",
    "pos": "noun / adjective",
    "ipa": "",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "nyeic",
    "eng": "two (secondary set)",
    "pos": "noun / adjective",
    "ipa": "ɲɛɪ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "faam",
    "eng": "three (secondary set)",
    "pos": "noun / adjective",
    "ipa": "fam˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "feix",
    "eng": "four (secondary set)",
    "pos": "noun / adjective",
    "ipa": "fɛɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "hmz",
    "eng": "five (secondary set)",
    "pos": "noun / adjective",
    "ipa": "m̥˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "luoqc",
    "eng": "six (secondary set)",
    "pos": "noun / adjective",
    "ipa": "luəʔ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "cietv",
    "eng": "seven (secondary set)",
    "pos": "noun / adjective",
    "ipa": "ciətʰ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "betv",
    "eng": "eight (secondary set)",
    "pos": "noun / adjective",
    "ipa": "b’etʰ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "juov",
    "eng": "nine (secondary set)",
    "pos": "noun / adjective",
    "ipa": "t͡ɕuə˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’yietv",
    "eng": "first, position one in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’jiətʰ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’nyeic",
    "eng": "second, position two in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’ɲɛɪ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’faam",
    "eng": "third, position three in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’fam˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’feix",
    "eng": "fourth, position four in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’fɛɪ˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’hmz",
    "eng": "fifth, position five in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’m̥˨˧",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’luoqc",
    "eng": "sixth, position six in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’luəʔ˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’cietv",
    "eng": "seventh, position seven in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’ciətʰ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’betv",
    "eng": "eighth, position eight in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’b’etʰ˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’juov",
    "eng": "ninth, position nine in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’t͡ɕuə˦˥",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "da’ziepc",
    "eng": "tenth, position ten in an order",
    "pos": "noun / adjective",
    "ipa": "tɐ’ziəb’˨˩",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "haiz",
    "eng": "to hear",
    "pos": "verb",
    "ipa": "",
    "mex1": "Yie haiz ntu meih.",
    "mtr1": "I can’t hear you.",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "haih",
    "eng": "to know how to, be able to do something",
    "pos": "verb",
    "ipa": "",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  },
  {
    "mien": "gapv",
    "eng": "to put together",
    "pos": "verb",
    "ipa": "",
    "mex1": "",
    "mtr1": "",
    "mex2": "",
    "mtr2": "",
    "extranotes": ""
  }
]

export const CVT = [
  {
    "Letters": "b",
    "c_mien_example": "buoz",
    "c_english_meaning": "hand",
    "IPA": "b’",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "c",
    "c_mien_example": "cie",
    "c_english_meaning": "car",
    "IPA": "tsʰ",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "d",
    "c_mien_example": "dang",
    "c_english_meaning": "light",
    "IPA": "t",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "f",
    "c_mien_example": "faang",
    "c_english_meaning": "suitcase, chest",
    "IPA": "f",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "g",
    "c_mien_example": "gaengv",
    "c_english_meaning": "frog",
    "IPA": "k’",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "h",
    "c_mien_example": "heh",
    "c_english_meaning": "shoe",
    "IPA": "h",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "hl",
    "c_mien_example": "hlaax",
    "c_english_meaning": "month",
    "IPA": "l̥",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "hm",
    "c_mien_example": "hmien",
    "c_english_meaning": "face",
    "IPA": "m̥",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "hn",
    "c_mien_example": "hnaav",
    "c_english_meaning": "crossbow",
    "IPA": "n̥",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "hng",
    "c_mien_example": "hngaqv",
    "c_english_meaning": "chop",
    "IPA": "ŋ̊",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "hny",
    "c_mien_example": "hnyouv",
    "c_english_meaning": "heart",
    "IPA": "ɲ̥",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "j",
    "c_mien_example": "jaux",
    "c_english_meaning": "egg",
    "IPA": "t͡ɕ",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "k",
    "c_mien_example": "korqv",
    "c_english_meaning": "gourd",
    "IPA": "kʰ",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "l",
    "c_mien_example": "lui",
    "c_english_meaning": "Horse",
    "IPA": "l",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "m",
    "c_mien_example": "maaz",
    "c_english_meaning": "shirt",
    "IPA": "m",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "mb",
    "c_mien_example": "mbing",
    "c_english_meaning": "monkey",
    "IPA": "b",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "n",
    "c_mien_example": "naauz",
    "c_english_meaning": "mouse",
    "IPA": "n",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "nd",
    "c_mien_example": "ndiangx",
    "c_english_meaning": "tree",
    "IPA": "d",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "ng",
    "c_mien_example": "ngongh",
    "c_english_meaning": "cow",
    "IPA": "ŋ",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "nj",
    "c_mien_example": "njiuz",
    "c_english_meaning": "scissors",
    "IPA": "d͡ʑ",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "nq",
    "c_mien_example": "nqaai",
    "c_english_meaning": "dry",
    "IPA": "g",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "nz",
    "c_mien_example": "nzangv",
    "c_english_meaning": "canoe",
    "IPA": "d͡z",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "ny",
    "c_mien_example": "nyanc",
    "c_english_meaning": "to eat",
    "IPA": "ɲ",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "p",
    "c_mien_example": "porng",
    "c_english_meaning": "hoe",
    "IPA": "b’",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "q",
    "c_mien_example": "qaa",
    "c_english_meaning": "shrimp",
    "IPA": "t͡ɕʰ",
    "CVT": "IC",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "q",
    "c_mien_example": "zuqc",
    "c_english_meaning": "must",
    "IPA": "ʔ",
    "CVT": "FC",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "s",
    "c_mien_example": "sou",
    "c_english_meaning": "book",
    "IPA": "S",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "t",
    "c_mien_example": "tei",
    "c_english_meaning": "ladder",
    "IPA": "tʰ",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "w",
    "c_mien_example": "waac",
    "c_english_meaning": "language",
    "IPA": "w",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "y",
    "c_mien_example": "yungh",
    "c_english_meaning": "goat",
    "IPA": "j",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "z",
    "c_mien_example": "zaandgz",
    "c_english_meaning": "elephant",
    "IPA": "t͡s",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "r",
    "c_mien_example": "rimot",
    "c_english_meaning": "remote",
    "IPA": "ɹ",
    "CVT": "C",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "a",
    "c_mien_example": "ga’sie",
    "c_english_meaning": "stomach",
    "IPA": "ɐ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "aa",
    "c_mien_example": "maa",
    "c_english_meaning": "mother",
    "IPA": "a",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "ae",
    "c_mien_example": "dae",
    "c_english_meaning": "father",
    "IPA": "æ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "ai",
    "c_mien_example": "lai",
    "c_english_meaning": "vegetable",
    "IPA": "aɪ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "aai",
    "c_mien_example": "laai",
    "c_english_meaning": "last",
    "IPA": "aːɪ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "au",
    "c_mien_example": "dau",
    "c_english_meaning": "answer",
    "IPA": "aʊ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "aau",
    "c_mien_example": "daau",
    "c_english_meaning": "palm tree",
    "IPA": "aːʊ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "e",
    "c_mien_example": "gen",
    "c_english_meaning": "bedroom",
    "IPA": "e",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "ei",
    "c_mien_example": "tei",
    "c_english_meaning": "ladder",
    "IPA": "ɛɪ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "er",
    "c_mien_example": "sern",
    "c_english_meaning": "meat salad",
    "IPA": "ɜ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "eu",
    "c_mien_example": "beu",
    "c_english_meaning": "to wrap",
    "IPA": "ɜo",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "i",
    "c_mien_example": "ki",
    "c_english_meaning": "to look down upon",
    "IPA": "i",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "ie",
    "c_mien_example": "cie",
    "c_english_meaning": "car",
    "IPA": "iə",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "o",
    "c_mien_example": "hlo",
    "c_english_meaning": "big",
    "IPA": "o",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "oi",
    "c_mien_example": "koi",
    "c_english_meaning": "to open",
    "IPA": "oɪ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "or",
    "c_mien_example": "tor",
    "c_english_meaning": "to pull, drag",
    "IPA": "ɒ",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "ou",
    "c_mien_example": "jiou",
    "c_english_meaning": "mushroom",
    "IPA": "əu",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "u",
    "c_mien_example": "du",
    "c_english_meaning": "chubby, plump",
    "IPA": "u",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "ui",
    "c_mien_example": "lui",
    "c_english_meaning": "shirt",
    "IPA": "ui",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "uo",
    "c_mien_example": "buo",
    "c_english_meaning": "three",
    "IPA": "uə",
    "CVT": "V",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "none",
    "c_mien_example": "maai",
    "c_english_meaning": "basic tail of bird",
    "IPA": "˧",
    "CVT": "T",
    "Note2": "",
    "Note2__1": ""
  },
  {
    "Letters": "v",
    "c_mien_example": "maaiv",
    "c_english_meaning": "lopsided",
    "IPA": "˦˥",
    "CVT": "T",
    "Note2": "High tone, dog tone",
    "Note2__1": ""
  },
  {
    "Letters": "x",
    "c_mien_example": "maaix",
    "c_english_meaning": "nightmare",
    "IPA": "˨˧",
    "CVT": "T",
    "Note2": "Softer, (rabbit tone)",
    "Note2__1": ""
  },
  {
    "Letters": "h",
    "c_mien_example": "maaih",
    "c_english_meaning": "to have",
    "IPA": "˧˩",
    "CVT": "T",
    "Note2": "Elongated flat tone, (cow tone)",
    "Note2__1": ""
  },
  {
    "Letters": "z",
    "c_mien_example": "maaiz",
    "c_english_meaning": "to buy",
    "IPA": "˨˧",
    "CVT": "T",
    "Note2": "Low rising, heavier, (horse tone)",
    "Note2__1": ""
  },
  {
    "Letters": "c",
    "c_mien_example": "maaic",
    "c_english_meaning": "to sell",
    "IPA": "˨˩",
    "CVT": "T",
    "Note2": "Low, (turtle tone)",
    "Note2__1": ""
  }
]